name: style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/ruff-action@v4.0.0
    - run: |
        ruff check --fix
        ruff format
